"""
Traffic recognition: To identify target segments releant to A and exclude those irrelavant to A
-> C-similarity => quentify how likely packets withing a target segment are generated by Z.
=> use hierarchical bag-of-words

input: from segmentation: s1,s2,...,s_m: the resuting clusters: the target segments
-> for a target segment s_t, its componential similarity with A is:
Psi^A(s_t) = the probability that there exists a packet in s_t generated by A
"""

from typing import List, Tuple, Dict, Any, Set
import numpy as np
from sklearn.tree import DecisionTreeClassifier
import math
import pickle
import numpy as np
from collections import defaultdict
import json
import os
import pandas as pd
